USE COMPANY_DB;

SHOW TABLES;

SELECT * FROM EMPLOYEES1;

-- SIMPLE CASE
SELECT NAME, DEPARTMENT,
CASE DEPARTMENT
	WHEN 'IT' THEN 'TECH TEAM'
    WHEN 'FINANCE' THEN 'FINANCE TEAM'
    ELSE 'HUMAN RESOURCES'
END AS NEW_DEPT
FROM EMPLOYEES1;


-- SEARCHED CASE
SELECT NAME, SALARY,
CASE 
	WHEN SALARY > 50000 THEN 'HIGH PAY'
    WHEN SALARY > 20000 THEN 'MEDIUM PAY'
    ELSE ' LOW PAY'
END AS SALARY_PAY
FROM EMPLOYEES1;