CREATE DATABASE CONSTRAINTS_DB;

USE CONSTRAINTS_DB;

-- TABLE 1

CREATE TABLE EMP
(
E_ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(30) NOT NULL,
AGE INT CHECK(AGE > 18),
DOJ DATE,
EMAIL VARCHAR(50) UNIQUE,
CITY VARCHAR(20) DEFAULT "HYD"
);

DESC EMP;

INSERT INTO EMP(NAME, AGE, DOJ, EMAIL, CITY) VALUES
('SAI', 20, '2026-08-25', 'SAI@GMAIL.COM', 'PUNE'),
('KIRAN', 21, '2025-05-28', 'KIRAN@GMAIL.COM', DEFAULT);

SELECT * FROM EMP;

-- TABLE 2

CREATE TABLE EMP2
(
E_ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(30) NOT NULL,
AGE INT CHECK(AGE > 18),
DOJ DATE,
EMAIL VARCHAR(50) UNIQUE,
CITY VARCHAR(20) DEFAULT "HYD"
)AUTO_INCREMENT = 51;

INSERT INTO EMP2(NAME, DOJ, EMAIL, CITY) VALUES
('SAI', '2026-08-25', 'SAI@GMAIL.COM', 'PUNE'),
('KIRAN', '2025-05-28', 'KIRAN@GMAIL.COM', DEFAULT);


-- HOW TO ADD CONSTRAINTS AFTER CREATION OF TABLE
-- WITHOUT CONSTRAINTS

CREATE TABLE EMPLOYEES
(
ID INT,
NAME VARCHAR(30),
AGE INT,
DOJ DATE,
EMAIL VARCHAR(50),
CITY VARCHAR(20)
);

DESC EMPLOYEES;

-- TO ADD A PRIMARY KEY ON ID COLUMN
ALTER TABLE EMPLOYEES
MODIFY COLUMN ID INT PRIMARY KEY;

DESC EMPLOYEES;

-- TO ADD AUTO_INCREMENT ON ID COLUMN
ALTER TABLE EMPLOYEES
MODIFY COLUMN ID INT AUTO_INCREMENT;

DESC EMPLOYEES;

-- USE MULTIPLE MODIFY COLUMN
ALTER TABLE EMPLOYEES
MODIFY COLUMN NAME VARCHAR(30) NOT NULL,
MODIFY COLUMN AGE INT CHECK(AGE > 18),
MODIFY COLUMN EMAIL VARCHAR(50) UNIQUE,
MODIFY COLUMN CITY VARCHAR(30) DEFAULT "HYD";

DESC EMPLOYEES;

SHOW CREATE TABLE EMPLOYEES;

-- HOW TO DROP EACH AND EVERY CONSTRAINTS

-- 1. AUTO_INCREMENT (IT REMOVES AUTO INCREMENT COMMAND ON COLUMN)
ALTER TABLE EMPLOYEES
MODIFY COLUMN ID INT;

DESC EMPLOYEES;

-- TO REMOVE ALL OTHER CONSTRAINTS USING IN SINGLE ALTER COMMAND
ALTER TABLE EMPLOYEES
MODIFY COLUMN NAME VARCHAR(30) NULL,
MODIFY COLUMN CITY VARCHAR(30);

DESC EMPLOYEES;

-- DROP A PRIMARY KEY, UNIQUE, CHECK
ALTER TABLE EMPLOYEES
DROP PRIMARY KEY;

DESC EMPLOYEES;


-- SUDDENLY I AM DELETING THE EMAIL COLUMN, SO AGAIN I CREATE AND DROP UNIQUE KEY
ALTER TABLE EMPLOYEES
ADD COLUMN EMAIL VARCHAR(30) UNIQUE;

-- DROP UNIQUE KEY

ALTER TABLE EMPLOYEES
DROP CONSTRAINT EMAIL;

DESC EMPLOYEES;

-- DROP CHECK CONSTRAINT
ALTER TABLE EMPLOYEES
DROP CHECK empoloyees_chk_1;

DESC EMPLOYEES;