-- DATE AND TIME FUNCTIONS:
-- CURDATE() -- RETURNS CURRENT DATE
SELECT CURDATE() TODAYS_DATE;
SELECT CURRENT_DATE()TODAYS_DATE;

-- CURTIME() -- RETURNS CURRENT TIME (HH:MM:SS)
SELECT CURTIME() TIME_NOW;
SELECT CURRENT_TIME() TIME_NOW;

-- NOW() -- RETURNS CURRENT DATE AND TIME(YYYY-MM-DD HH:MM:SS)
SELECT NOW();

-- SYSDATE() -- RETURNS SYSTEM DATE AD TIME --EXECUTION TIME
SELECT SYSDATE();

-- DATE() -- EXTRACTS DATE PART FROM DATETIME VALUE
SELECT DATE('2026-06-17 12:30:08') D;

-- TIME() -- EXTRACTS TIME PART FROM DATETIME VALUE
SELECT TIME('2026-06-17 12:30:08') T;


-- YEAR(), MONTH(), DAY()
-- EXTRACTS INDIVIDUAL PARTS OF A DATE
SELECT YEAR('2026-06-17') Y, MONTH('2026-06-17') M, DAY('2026-06-17') D;

-- DAYNAME() -- RETURNS WEEKDAY NAME FOR A GIVEN DATE
SELECT DAYNAME('2026-06-17') D_NAME;

-- MONTHNAME() -- RETURNS MONTH NAME FOR A GIVEN DATE
SELECT MONTHNAME('2026-06-17') M_NAME;

-- DATE_FORMAT() -- FORMATS DATE USING SPECIFIC FORMAT SPECIFIERS
SELECT DATE_FORMAT('2026-06-17', '%d/%m/%Y') D;


-- COMMON FORMATS
-- %Y --> YEAR (4 DIGITS)
-- %m --> MONTH (2 DIGITS)
-- %M --> MONTH NAME
-- %d --> DAY
-- %W --> WEEKDAY NAME
-- %H --> HOUR (24 HOUR FORMAT)
-- %i --> MINUTES
-- %s --> SECONDS


-- DATEDIFF()
-- RETURNS THE DIFFERENCE BETWEEN TWO DATES IN DAYS
SELECT DATEDIFF('2026-06-17', '2025-12-12') DATE_DIFF;

-- ADDDATE() / DATE_ADD()
-- ADDS A SPECIFIC TIME INTERVAL TO DATE
SELECT DATE_ADD('2026-06-17', INTERVAL 10 DAY) D;
SELECT DATE_ADD('2026-06-17', INTERVAL 10 MONTH) M;

-- SUBDATE() / DATE_SUB()
SELECT DATE_SUB('2026-06-17', INTERVAL 10 MONTH) M;

-- ADDTIME()
SELECT ADDTIME('2025-11-10 05:00:00', '02:30:15') T;

-- SUBTIME()
SELECT SUBTIME('2025-11-10 05:00:00', '02:30:15') T;


-- TIMEDIFF()
-- RETURNS THE DIFFERENCE BETWEEN TWO TIMES
SELECT TIMEDIFF('05:00:00', '02:30:15') T;

-- EXTRACT() -- EXTRACTS A SPECIFIC PART(Y,M,D,H,M,S) FROM DATETIME
SELECT EXTRACT(DAY FROM '2025-11-10 05:00:00') E;
