USE SUBQUERIES;

SELECT * FROM EMPLOYEES;

-- COMMIT
INSERT INTO EMPLOYEES VALUES
(6, 'F', 'HR', 45000);

COMMIT;

SELECT * FROM EMPLOYEES;

-- ROLLBACK
-- CHANGING 1 - ROW SALARY FROM 55000 TO 60000
UPDATE EMPLOYEES 
SET SALARY = 60000
WHERE EMPID = 1;

SELECT * FROM EMPLOYEES;

-- CHANGING 4-ROW SALARY FROM 70000 TO 60000
UPDATE EMPLOYEES
SET SALARY = 60000
WHERE EMPID = 4;

ROLLBACK;         -- IT UNDO VALUES ON 1-ROW AND 4-ROW CHANGES RESTORE AGAIN.

SELECT * FROM EMPLOYEES;


-- SAVE POINT
UPDATE EMPLOYEES 
SET SALARY = 60000
WHERE EMPID = 1;

SAVEPOINT SP1;

SELECT * FROM EMPLOYEES;

-- CHANGING 4-ROW SALARY FROM 70000 TO 60000
UPDATE EMPLOYEES
SET SALARY = 60000
WHERE EMPID = 4;

SAVEPOINT SP2;

SELECT * FROM EMPLOYEES;

ROLLBACK TO SAVEPOINT SP1;

SELECT * FROM EMPLOYEES;

COMMIT;

SELECT * FROM EMPLOYEES;