SELECT 1;

-- TO SEE DEFAULT DATABASES

SHOW DATABASES;

-- CREATE A DATABASES
CREATE DATABASE COMPANY_DB;

-- ENTER THE DATABASE
USE COMPANY_DB;

-- CREATE A TABLE EMPLOYEES
SHOW DATABASES;

-- CURRENT DATABASE
SELECT DATABASE();

-- CREATE A TABLE EMPLOYEES
CREATE TABLE EMPLOYEES
(
ID INT,
NAME VARCHAR(30),
AGE INT,
DOJ DATE
);

-- TO SEE TABLES IN THE DATABASE
SHOW TABLES;

USE COMPANY_DB;

-- ALTER COMMAND

-- RENAME A TABLE
ALTER TABLE EMPLOYEES
RENAME TO EMP_DETAILS;

SHOW TABLES;

-- RENAME A COLUMN
ALTER TABLE EMP_DETAILS
RENAME COLUMN DOJ TO DATE_OF_JOINING;

-- DESCRIBE TABLE NAME
DESC EMP_DETAILS;

-- ADD COLUMN

-- By default the new Column will Add in Last Position
ALTER TABLE EMP_DETAILS
ADD COLUMN EMAIL VARCHAR(30);

DESC EMP_DETAILS;

-- ADD Column at a PFID at First Position before ID Column
ALTER TABLE EMP_DETAILS
ADD COLUMN PFID INT FIRST;

DESC EMP_DETAILS;

-- Adding the column at Particular Position Or in Between the Column
ALTER TABLE EMP_DETAILS
ADD COLUMN CITY VARCHAR(20) AFTER AGE;

DESC EMP_DETAILS;

-- DROP COLUMN

ALTER TABLE EMP_DETAILS
DROP COLUMN PFID;

DESC EMP_DETAILS;

-- MODIFY DATATYPE/SIZE

-- CHANGE DATA TYPE
ALTER TABLE EMP_DETAILS
MODIFY COLUMN AGE SMALLINT;  

-- CHANGES SIZE
ALTER TABLE EMP_DETAILS
MODIFY COLUMN CITY VARCHAR(30);

DESC EMP_DETAILS;

-- DROP A DATABASE OR A TABLE

-- DROP DATABASE COMPANY_DB;
-- DROP TABLE EMP_DETAILS;

-- TRUNCATE

-- TRUNCATE TABLE EMP_DETAILS;

