USE SUBQUERIES;

SELECT * FROM EMPLOYEES;

-- IN SELECT CLAUSE:
-- SHOW EACH EMPLOYEES SALARY WITH THE HIGHEST SALARY
SELECT ENAME, SALARY, (SELECT MAX(SALARY) FROM EMPLOYEES) HIGHEST_SAL
FROM EMPLOYEES;

-- IN HAVING CLAUSE:
-- LIST THE DEPARTMENTS WHOSE AVERAGE SALARY > AVERAGE SALARY OF T
SELECT DEPARTMENT, AVG(SALARY) AVG_SAL
FROM EMPLOYEES
GROUP BY DEPARTMENT
HAVING AVG_SAL > (SELECT AVG(SALARY) FROM EMPLOYEES);


-- DERIVED TABLE (FROM CLAUSE):
-- FIND ALL DEPARTMENTS WHOSE AVERAGE SALARY IS GREATER THAN 55000
SELECT DEPARTMENT, AVG_SAL
FROM (SELECT DEPARTMENT, AVG(SALARY) AVG_SAL
		FROM EMPLOYEES
        GROUP BY DEPARTMENT) DEPT_AVGSAL
WHERE AVG_SAL > 55000;


-- CTE (COMMON TABLE EXPRESSION):
-- FIND ALL DEPARTMENTS WHOSE AVERAGE SALARY IS GREATER THAN 55000
WITH DEPT_AVGSAL AS
(
SELECT DEPARTMENT, AVG(SALARY) AVG_SAL
FROM EMPLOYEES
GROUP BY DEPARTMENT
)
SELECT DEPARTMENT, AVG_SAL FROM DEPT_AVGSAL
WHERE AVG_SAL > 55000;

SELECT * FROM DEPT_AVGSAL;


-- VIEW:
-- FIND ALL DEPARTMENTS WHOSE AVERAGE SALARY IS GREATER THAN 55000
CREATE VIEW DEPT_AVGSAL AS
SELECT DEPARTMENT, AVG(SALARY) AVG_SAL
FROM EMPLOYEES
GROUP BY DEPARTMENT;

SELECT * FROM DEPT_AVGSAL;

SELECT DEPARTMENT, AVG_SAL
FROM DEPT_AVGSAL
WHERE AVG_SAL > 55000;