-- DML, DQL COMMANDS

USE COMPANY_DB;

ALTER TABLE EMP_DETAILS
DROP COLUMN EMAIL;

-- INSERT 
INSERT INTO EMP_DETAILS(ID, NAME, AGE, DATE_OF_JOINING) VALUES
(1, 'SAI', 20, '2025-04-26'),
(2, 'KIRAN', 21, '2026-08-25'),
(3, 'RAM', 22, '2025-05-15');

-- SELECT 
SELECT * FROM EMP_DETAILS;


-- UPDATE 
UPDATE EMP_DETAILS
SET AGE = 30
WHERE NAME = 'RAM';

SET SQL_SAFE_UPDATE = 0;

SELECT * FROM EMP_DETAILS;


-- DELETE
DELETE FROM EMP_DETAILS
WHERE ID = 3;

SELECT * FROM EMP_DETAILS;