USE SUBQUERIES;

SELECT * FROM EMPLOYEES;


-- STORED PROCEDURE:
-- CREATE A PROCEDURE TO STORE DEPT AND THEIR AVG SALARIES
DELIMITER $$
CREATE PROCEDURE DEPT_AVGSAL()
BEGIN
SELECT DEPARTMENT, AVG(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT;
END $$
DELIMITER ;

CALL DEPT_AVGSAL();


/* CREATE A PROCEDURE TO STORE DEPARTMENT AND IT'S AVERAGE SALARY 
 WHICH TAKES DEPARTMENT NAME AS INPUT */
 DELIMITER //
 CREATE PROCEDURE DEPT_AVG_SAL_IN1(
						IN DEPT_NAME VARCHAR(30))
BEGIN
SELECT DEPARTMENT, AVG(SALARY)
FROM EMPLOYEES
WHERE FIND_IN_SET(DEPARTMENT, DEPT_NAME)
GROUP BY DEPARTMENT;
END //
DELIMITER ;       

CALL DEPT_AVG_SAL_IN1('FINANCE,IT'); 

                
/* CREATE A PROCEDURE TO UPDATE EMPLOYEE AND HIS SALARY WITH A PERCENT RAISE 
 WHICH TAKES EMPID AND PERCENT RAISE AS INPUT */
 DELIMITER $$
 CREATE PROCEDURE UPD_SAL_RAISE1(
					IN E_ID INT,
                    IN P_RAISE INT)
BEGIN
UPDATE EMPLOYEES
SET SALARY = SALARY * (1 + P_RAISE/100)
WHERE EMPID = E_ID;
SELECT ENAME, SALARY FROM EMPLOYEES
WHERE EMPID = E_ID;
END $$
DELIMITER ;

CALL UPD_SAL_RAISE1(3, 10);

SELECT * FROM EMPLOYEES;

 