CREATE DATABASE SUBQUERIES;

USE SUBQUERIES;

CREATE TABLE EMPLOYEES(
EMPID INT PRIMARY KEY,
ENAME VARCHAR(50),
DEPARTMENT VARCHAR(50),
SALARY INT 
);

INSERT INTO EMPLOYEES(EMPID, ENAME, DEPARTMENT, SALARY)VALUES
(1,'A','HR',55000),
(2,'B','IT',60000),
(3,'C','FINANCE',55000),
(4,'D','IT',70000),
(5,'E','FINANCE',75000);

SELECT * FROM EMPLOYEES;


-- SINGLE ROW / SCALAR SUBQUERY:
-- FIND EMPLOYEE WITH HIGHEST SALARY
SELECT ENAME, SALARY
FROM EMPLOYEES
WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES);

-- OR
SELECT MAX(SALARY) FROM EMPLOYEES;

-- FIND EMPLOYEES WHOSE SALARY IS SAME AS LOWEST SALARY IN IT
SELECT ENAME, SALARY
FROM EMPLOYEES
WHERE SALARY  = (SELECT MIN(SALARY) FROM EMPLOYEES
					WHERE DEPARTMENT = 'IT');
                    
-- OR
SELECT MIN(SALARY) FROM EMPLOYEES
WHERE DEPARTMENT = 'IT';
   
   
-- MULTI-ROW SUBQUERY:
-- FIND EMPLOYEES WHOSE SALARY IS SAME AS FINANCE DEPARTMENT SALARIES EXCEPT FINANCE
SELECT SALARY
FROM EMPLOYEES
WHERE DEPARTMENT = 'FINANCE';

-- OR
SELECT ENAME, SALARY, DEPARTMENT
FROM EMPLOYEES
WHERE DEPARTMENT != 'FINANCE' AND SALARY IN (SELECT SALARY
FROM EMPLOYEES
WHERE DEPARTMENT = 'FINANCE');


-- CORRELATED SUBQUERY
-- FIND EMPLOYEE WHO IS EARNING MORE THAN AVERAGE SALARY OF THEIR DEPARTMENT
 
SELECT E1.ENAME, E1.SALARY, E1.DEPARTMENT
FROM EMPLOYEES E1
WHERE E1.SALARY > (SELECT AVG(E2.SALARY)
				FROM EMPLOYEES E2
				WHERE E2.DEPARTMENT = E1.DEPARTMENT);
                