CREATE DATABASE WINDOWfUNCTIONS;

USE WINDOWfUNCTIONS;

CREATE TABLE STUDENT_MARKS (
  STUDENT_ID INT PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  SUBJECT VARCHAR(50) NOT NULL,
  MARKS INT NOT NULL
);

INSERT INTO STUDENT_MARKS (STUDENT_ID, NAME, SUBJECT, MARKS) VALUES
  (101, 'ARJUN',  'MATHS',   95),
  (102, 'KIRAN',  'MATHS',   90),
  (103, 'NEHA',   'MATHS',   90),
  (104, 'SAI',    'MATHS',   85),
  (105, 'PRIYA',  'SCIENCE', 98),
  (106, 'AMIT',   'SCIENCE', 92),
  (107, 'RAHUL',  'SCIENCE', 92),
  (108, 'VIKAS',  'SCIENCE', 80);
  
  SELECT * FROM STUDENT_MARKS;
  
-- 1. ROW_NUMBER()
SELECT NAME, SUBJECT, MARKS,
	ROW_NUMBER() OVER (PARTITION BY SUBJECT ORDER BY MARKS DESC) RN
FROM STUDENT_MARKS; 

-- 2. RANK(), 3. DENSE_RANK(), 4. PERCENT_RANK(), 5. NTITLE()
SELECT NAME, SUBJECT, MARKS,
		RANK() OVER (PARTITION BY SUBJECT ORDER BY MARKS DESC) RN,
		DENSE_RANK() OVER (PARTITION BY SUBJECT ORDER BY MARKS DESC) DR,
		PERCENT_RANK() OVER (PARTITION BY SUBJECT ORDER BY MARKS DESC) PR,
		NTILE(3) OVER (PARTITION BY SUBJECT ORDER BY MARKS DESC) N3,
		NTILE(4) OVER (PARTITION BY SUBJECT ORDER BY MARKS DESC) N4,
		NTILE(5) OVER (PARTITION BY SUBJECT ORDER BY MARKS DESC) N5
FROM STUDENT_MARKS;

-- 6. LEAD(), 7. LAG()
SELECT NAME, SUBJECT, MARKS,
	LEAD(MARKS) OVER (PARTITION BY SUBJECT ORDER BY MARKS DESC) LD,
    LAG(MARKS) OVER (PARTITION BY SUBJECT ORDER BY MARKS DESC) LG
FROM STUDENT_MARKS; 

-- 8. FIRST_VALUE()
SELECT NAME, SUBJECT, MARKS,
	FIRST_VALUE(MARKS) OVER (PARTITION BY SUBJECT ORDER BY MARKS DESC) FV
FROM STUDENT_MARKS; 

-- 9. LAST_VALUE()

SELECT NAME, SUBJECT, MARKS,
	LAST_VALUE(MARKS) OVER (PARTITION BY SUBJECT ORDER BY MARKS DESC 
    ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) LV
FROM STUDENT_MARKS; 

-- UNBOUNDED PRECEDING MEANS "EXTREM FIRST ROW"
-- UNBOUNDED FOLLOWING MEANS "EXTREM LAST ROW"

-- 10. CUME_DIST()
SELECT NAME, SUBJECT, MARKS,
	CUME_DIST() OVER (PARTITION BY SUBJECT ORDER BY MARKS DESC) FCD
FROM STUDENT_MARKS;